{% set name = "tblite-python" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tblite/tblite/releases/download/v{{ version }}/tblite-{{ version }}-python-sdist.tar.gz
  sha256: 281f5aa56a68b897e91df87620b315121fa6b2d5564e058d90364375da496ba3

build:
  number: 2
  skip: true  # [osx and py<38]
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [osx and arm64]
    - meson
    - ninja
    - python
    - pkg-config
  host:
    - cffi
    - pip
    - python
    - tblite {{ version }}
  run:
    - cffi
    - numpy
    - python


test:
  imports:
    - tblite
    - tblite.library
    - tblite.interface
  requires:
    - pip
    - pytest
    - ase
  commands:
    - pip check
    - pytest --pyargs tblite -vv

about:
  home: https://pypi.org/project/tblite
  dev_url: https://github.com/tblite/tblite
  doc_url: https://tblite.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - subprojects/tblite/COPYING
    - subprojects/tblite/COPYING.LESSER
  summary: Python API for the tblite project

extra:
  recipe-maintainers:
    - awvwgk
